services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
    environment:
      - APP_PUBLIC_PATH=${APP_PUBLIC_PATH:-/var/www/html}
      - SSH_PASSWORD=${SSH_PASSWORD:-p}
    ports:
      - "${SSH_PORT:-5555}:22"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/", "||", "exit", "1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      # Application data
      - app_data:/var/www/html
      # Configuration files
      - ./config/php-recommended.ini:/usr/local/etc/php/conf.d/php-recommended.ini:ro
      - ./config/apcu.ini:/usr/local/etc/php/conf.d/apcu.ini:ro
      - ./config/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      # SSH persistent data
      - php_ssh_config:/home/appuser/.ssh
      - php_ssh_host_keys:/etc/ssh
    # Add extra hosts to resolve host.docker.internal on Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_net

  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Nginx as a simple proxy to Apache
  nginx-proxy:
    image: nginx:alpine
    restart: always
    depends_on:
      - php
    # ports:
    #   # Only expose HTTP port 8005
    #   - "8005:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - app_data:/var/www/html:ro
    networks:
      - app_net

  # VS Code Web (code-server) for browser-based development
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    restart: always
    environment:
      - PUID=33
      - PGID=33
      - TZ=UTC
      - PASSWORD=${CODE_SERVER_PASSWORD:-password}
      - DEFAULT_WORKSPACE=/config/workspace
      - SHELL=/bin/bash
    volumes:
      - app_data:/config/workspace
      - code_server_config_data:/config
    ports:
      - "${CODE_SERVER_PORT:-8443}:8443"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  redis_data:
  app_data:
  php_ssh_config:
  php_ssh_host_keys:
  code_server_config_data:
