services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/", "||", "exit", "1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./app:/var/www/html
